[package]
name = "cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "web3-backend"
path = "src/main.rs"

[dependencies]
app-core = { path = "../core" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { version = "4", features = ["derive"] }
csv = "1"